language: node_js
services:
  - mongodb
install:
  - npm install
  - npm install -g mocha
  - npm install -g codecov
  - npm install -g istanbul
script:
  - istanbul cover mocha --report lcovonly -- -R spec
  - codecov
